project:
  type: website
  output-dir: docs


website:
  title: "Henry Gliedman Personal Webpage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: maps.qmd
        text: Maps
      - href: miniproject2.qmd
        text: MiniProject2
page-footer:
    left: |
      &copy; Henry Gliedman, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

